### ISSUE TITLE
Download link at codeplex.com not working

### ISSUE THREAD

**Issue by anjdreas** [cplotts/snoopwpf#59]
Maybe it is a temporary issue, but here is a zipped copy of the binaries for anyone's convenience. Codeflex is entirely shut down in December 2017, so I assume any download links over there will be gone then as well.

NOTE: THESE ARE NOT THE OFFICIAL FILES!
Run at your own risk. They are based on the files uploaded at Chocolatey: https://chocolatey.org/packages/snoop
It does not have the .msi installer, but I'm sure that can be sourced somewhere too.

[Snoop-2.8.0.zip](https://github.com/cplotts/snoopwpf/files/1124352/Snoop-2.8.0.zip)

**Comment by cplotts** [comment]
I was just able to download it. Is anyone else having problems? If so, please let me know. I suppose when CodePlex goes down I will make the binaries available via my blog www.cplotts.com since GitHub doesn't let you do that anymore.

**Comment by anjdreas** [comment]
Yes it works now to me as well, was probably just a temporary fluke. Just a tip, you can upload files by starting a new github issue and uploading a file to it. The file is then hosted by github, but I have no idea what the lifetime guarantee is for those types of files.

**Comment by cplotts** [comment]
Yeah I noticed that you attached the .zip file with the binaries and was a little bit surprised by that ... given that they made a big effort to make GitHub only about sharing source code a while back (and not binaries). But, at the same time, I am not surprised, as I am sure they didn't want to stop people from uploading screenshots and the like ... in order to make troubleshooting of issues easier. Regardless, the previous binaries area is gone.

Glad it was just a temporary CodePlex issue.
